apiVersion: v1
kind: Service
metadata:
  name: alpha
  labels:
    app: alpha
    service: alpha
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
  labels:
    app: alpha
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha
      version: v1
  template:
    metadata:
      labels:
        app: alpha
        version: v1
    spec:
      containers:
      - name: alpha
        image: alpha:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
