apiVersion: v1
kind: Service
metadata:
  name: beta
  labels:
    app: beta
    service: beta
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: beta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  labels:
    app: beta
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beta
      version: v1
  template:
    metadata:
      labels:
        app: beta
        version: v1
    spec:
      hostname: beta
      containers:
      - name: beta
        image: beta:v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
