apiVersion: v1
kind: Service
metadata:
  name: garden
  labels:
    app: garden
    service: garden
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: garden
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-v1
  labels:
    app: garden
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden
      version: v1
  template:
    metadata:
      labels:
        app: garden
        version: v1
    spec:
      containers:
      - name: garden
        image: garden:v20240222.1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
